# Generated by Django 5.2.17 on 2026-08-21 15:03

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=255)),
                ("natural_key", models.CharField(max_length=255)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("seller_key", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("source_key", models.CharField(blank=True, max_length=128, null=True)),
                ("is_panel", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("standard", "Standard"),
                            ("trusted", "Trusted"),
                            ("suspended", "Suspended"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("trust_score", models.DecimalField(decimal_places=6, default=0, max_digits=7)),
                (
                    "price_accuracy",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
                ),
                (
                    "stock_accuracy",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
                ),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "wallet_balance_toman",
                    models.BigIntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("panel_offers_active", models.BooleanField(default=True)),
                ("billing_state_version", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["seller_key"],
            },
        ),
        migrations.CreateModel(
            name="SuspicionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("threshold", models.PositiveIntegerField(default=1)),
                ("window_seconds", models.PositiveIntegerField(default=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CpcRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "min_price_toman",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("max_price_toman", models.BigIntegerField(blank=True, null=True)),
                (
                    "cost_toman",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["min_price_toman", "effective_from"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_price_toman__isnull", True),
                            ("max_price_toman__gt", models.F("min_price_toman")),
                            _connector="OR",
                        ),
                        name="cpc_rate_valid_band",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "click_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("product_uid", models.UUIDField()),
                ("offer_uid", models.CharField(max_length=32)),
                ("seller_key", models.CharField(db_index=True, max_length=128)),
                ("price_toman", models.BigIntegerField(blank=True, null=True)),
                ("is_panel_offer", models.BooleanField()),
                (
                    "cost_toman",
                    models.BigIntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("is_suspicious", models.BooleanField(db_index=True, default=False)),
                ("fraud_reasons", models.JSONField(default=list)),
                ("ip_hash", models.CharField(max_length=64)),
                ("user_agent_hash", models.CharField(max_length=64)),
                ("fingerprint_hash", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.cpcrate",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("message_key", models.CharField(max_length=255)),
                ("natural_key", models.CharField(max_length=255)),
                ("body", models.JSONField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("publish_attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("topic", "natural_key"), name="outbox_topic_natural_key_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("charge", "Charge"),
                            ("topup", "Top-up"),
                            ("manual", "Manual adjustment"),
                        ],
                        max_length=16,
                    ),
                ),
                ("amount_toman", models.BigIntegerField()),
                (
                    "balance_after_toman",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "click",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_transaction",
                        to="billing.clickevent",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="billing.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="clickevent",
            index=models.Index(
                fields=["seller_key", "occurred_at"], name="billing_cli_seller__fc7d19_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference__isnull", False)),
                fields=("reference",),
                name="wallet_transaction_unique_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_toman", 0), _negated=True),
                name="wallet_transaction_nonzero_amount",
            ),
        ),
    ]
