# Generated by Django 5.2.17 on 2026-08-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeadLetterEvent",
            fields=[
                ("event_id", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=200)),
                ("reason", models.TextField()),
                ("message", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OfferReadModel",
            fields=[
                ("offer_uid", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("source_key", models.CharField(max_length=100)),
                ("external_key", models.TextField()),
                ("seller_key", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=1000)),
                ("raw_title", models.TextField()),
                ("title_normalized", models.TextField()),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "part_number",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                (
                    "part_type",
                    models.CharField(blank=True, db_index=True, max_length=100, null=True),
                ),
                ("price_toman", models.BigIntegerField(blank=True, null=True)),
                ("vehicle_hints", models.JSONField(default=list)),
                ("vehicle_hints_excluded", models.JSONField(default=list)),
                ("overbroad_claim", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("group_key", models.CharField(db_index=True, max_length=300)),
                ("trace_id", models.CharField(max_length=200)),
                ("source_occurred_at", models.DateTimeField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("output_hash", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["offer_uid"],
            },
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("event_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("topic", models.CharField(db_index=True, max_length=200)),
                ("message_key", models.CharField(max_length=300)),
                ("envelope", models.JSONField()),
                ("dedupe_key", models.CharField(max_length=500, unique=True)),
                ("trace_id", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("publish_attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                ("event_id", models.UUIDField(primary_key=True, serialize=False)),
                ("topic", models.CharField(max_length=200)),
                ("natural_key", models.CharField(max_length=300)),
                ("occurred_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["processed_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskyPartFamily",
            fields=[
                ("part_type", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("required_granularity", models.CharField(max_length=50)),
                ("note_fa", models.TextField()),
            ],
            options={
                "verbose_name_plural": "risky part families",
                "ordering": ["part_type"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("slug", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("trim", models.CharField(blank=True, max_length=100, null=True)),
                ("year_from", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("year_to", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("engine_code", models.CharField(blank=True, max_length=50, null=True)),
                ("display_name_fa", models.CharField(max_length=200)),
                ("aliases", models.JSONField(default=list)),
                ("is_published", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["brand", "model", "trim", "slug"],
            },
        ),
        migrations.CreateModel(
            name="CrossRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_a", models.CharField(max_length=100)),
                ("code_b", models.CharField(max_length=100)),
                ("brand_a", models.CharField(blank=True, max_length=100, null=True)),
                ("brand_b", models.CharField(blank=True, max_length=100, null=True)),
                ("confidence", models.FloatField()),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("rule", "Rule"),
                            ("model", "Model"),
                            ("human", "Human"),
                            ("catalog", "Catalog"),
                            ("consensus", "Consensus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code_a", "code_b"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code_a", "code_b"), name="crossref_pair_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PartFitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compatible", "Compatible"),
                            ("incompatible", "Incompatible"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField()),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("rule", "Rule"),
                            ("model", "Model"),
                            ("human", "Human"),
                            ("catalog", "Catalog"),
                            ("consensus", "Consensus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField()),
                (
                    "offer",
                    models.ForeignKey(
                        db_column="offer_uid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitments",
                        to="fitment.offerreadmodel",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_fitments",
                        to="fitment.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["offer_id", "vehicle_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("offer", "vehicle"), name="fitment_offer_vehicle_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HumanCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_uid", models.CharField(max_length=200, unique=True)),
                ("part_number", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compatible", "Compatible"),
                            ("incompatible", "Incompatible"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor", models.CharField(max_length=200)),
                ("reason", models.TextField(blank=True, null=True)),
                ("decided_at", models.DateTimeField()),
                ("trace_id", models.CharField(max_length=200)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="human_corrections",
                        to="fitment.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["part_number", "vehicle_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("part_number", "vehicle"), name="human_part_number_vehicle_unique"
                    )
                ],
            },
        ),
    ]
