# Generated by Django 5.2.17 on 2026-08-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRequestState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("part_number", models.CharField(max_length=100)),
                ("request_uid", models.CharField(max_length=200, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("skipped", "Skipped"),
                            ("settled", "Settled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_states",
                        to="fitment.vehicle",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("part_number", "vehicle"), name="review_part_number_vehicle_unique"
                    )
                ],
            },
        ),
    ]
