# Generated by Django 5.2.5 on 2026-08-21 08:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArchivedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.TextField()),
                ("url_hash", models.CharField(db_index=True, max_length=64)),
                ("http_status", models.PositiveSmallIntegerField()),
                ("fetched_at", models.DateTimeField(db_index=True)),
                ("last_seen_at", models.DateTimeField()),
                ("seen_count", models.PositiveIntegerField(default=1)),
                ("archive_uri", models.TextField()),
                ("page_hash", models.CharField(db_index=True, max_length=64)),
                ("error", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClickSignal",
            fields=[
                ("offer_uid", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("count_7d", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ConsumedClick",
            fields=[
                ("click_id", models.CharField(max_length=200, primary_key=True, serialize=False)),
                ("event_id", models.UUIDField(db_index=True)),
                ("offer_uid", models.CharField(db_index=True, max_length=32)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("matched", models.BooleanField(default=False)),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("base_url", models.URLField(max_length=500)),
                (
                    "kind",
                    models.CharField(
                        choices=[("html", "HTML"), ("feed", "Feed")], default="html", max_length=16
                    ),
                ),
                ("adapter_key", models.SlugField(max_length=64)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("politeness_delay_ms", models.PositiveIntegerField(default=2000)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-priority", "key"),
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_key", models.TextField()),
                ("offer_uid", models.CharField(db_index=True, max_length=32)),
                ("url", models.TextField()),
                ("url_hash", models.CharField(db_index=True, max_length=64)),
                ("raw_title", models.TextField()),
                ("raw_price_text", models.TextField(blank=True, null=True)),
                ("raw_stock_text", models.TextField(blank=True, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("raw_fragment", models.TextField()),
                ("fragment_hash", models.CharField(db_index=True, max_length=64)),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("trace_id", models.CharField(max_length=64)),
                ("emitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "archive_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="crawler.archiveddocument",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="crawler.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("dedupe_key", models.CharField(max_length=300, unique=True)),
                ("topic", models.CharField(max_length=200)),
                ("key", models.TextField()),
                ("body", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "observation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_event",
                        to="crawler.observation",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CrawlCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tier", models.CharField(max_length=64)),
                ("position", models.TextField(default="0")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_cursors",
                        to="crawler.source",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="archiveddocument",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archives",
                to="crawler.source",
            ),
        ),
        migrations.CreateModel(
            name="AdapterHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("window", models.DateTimeField(db_index=True)),
                ("attempted", models.PositiveIntegerField()),
                ("parsed_ok", models.PositiveIntegerField()),
                (
                    "parse_rate",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "baseline_rate",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("alerted", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_windows",
                        to="crawler.source",
                    ),
                ),
            ],
            options={
                "ordering": ("-window",),
            },
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["source", "external_key", "-observed_at"],
                name="crawler_obs_source__77ae55_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="crawlcursor",
            constraint=models.UniqueConstraint(
                fields=("source", "tier"), name="unique_source_tier_cursor"
            ),
        ),
        migrations.AddIndex(
            model_name="archiveddocument",
            index=models.Index(
                fields=["source", "url_hash", "-fetched_at"], name="crawler_arc_source__a89b90_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="archiveddocument",
            constraint=models.UniqueConstraint(
                fields=("source", "url_hash", "page_hash"), name="unique_archived_page_per_url"
            ),
        ),
    ]
