# Generated by Django 5.2.5 on 2026-08-21 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0002_seed_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="last_seen_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
