# Generated by Django, then hand-edited to make PriceHistory a partitioned
# table. See the SeparateDatabaseAndState block below.

import datetime
import uuid

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models

# Both PRIMARY KEY and UNIQUE must include the partition key: that is a
# Postgres rule for partitioned tables, not a preference. Django keeps `id`
# as the model's pk and never notices the composite.
CREATE_PRICE_HISTORY_SQL = """
CREATE TABLE catalog_pricehistory (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    offer_uid varchar(32) NOT NULL,
    product_uid uuid NULL,
    observed_at timestamptz NOT NULL,
    price_toman bigint NULL,
    stock_status varchar(16) NOT NULL DEFAULT 'unknown',
    PRIMARY KEY (id, observed_at),
    CONSTRAINT uniq_pricehistory_offer_observed UNIQUE (offer_uid, observed_at)
) PARTITION BY RANGE (observed_at);

CREATE INDEX catalog_pri_offer_u_320873_idx
    ON catalog_pricehistory (offer_uid, observed_at);
CREATE INDEX catalog_pri_product_401a5d_idx
    ON catalog_pricehistory (product_uid, observed_at);

-- The catch-all. An observation for a month nobody provisioned still lands
-- somewhere and stays queryable, instead of failing the insert that carries
-- it. `make_partitions` keeps real months ahead of the clock.
CREATE TABLE catalog_pricehistory_default PARTITION OF catalog_pricehistory DEFAULT;
"""


def _next_month(day: datetime.date) -> datetime.date:
    return (day.replace(day=28) + datetime.timedelta(days=4)).replace(day=1)


def create_initial_partitions(apps, schema_editor):
    """Provision a window around the deploy month.

    Backfill and replay both write history with old timestamps, and a month
    whose partition arrives *after* its rows have landed in the default
    partition cannot be created any more. A generous window up front means
    that effectively never happens.
    """
    today = datetime.date.today().replace(day=1)
    start = today
    for _ in range(12):
        start = (start - datetime.timedelta(days=1)).replace(day=1)

    month = start
    with schema_editor.connection.cursor() as cursor:
        for _ in range(25):  # 12 back, this month, 12 forward
            upper = _next_month(month)
            cursor.execute(
                f"CREATE TABLE IF NOT EXISTS catalog_pricehistory_{month:%Y_%m} "
                "PARTITION OF catalog_pricehistory FOR VALUES FROM (%s) TO (%s)",
                [month.isoformat(), upper.isoformat()],
            )
            month = upper


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrossRefReadModel",
            fields=[
                ("pair_key", models.CharField(max_length=257, primary_key=True, serialize=False)),
                ("code_a", models.CharField(db_index=True, max_length=128)),
                ("code_b", models.CharField(db_index=True, max_length=128)),
                ("brand_a", models.CharField(blank=True, max_length=128, null=True)),
                ("brand_b", models.CharField(blank=True, max_length=128, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("rule", "rule"),
                            ("model", "model"),
                            ("human", "human"),
                            ("catalog", "catalog"),
                            ("consensus", "consensus"),
                        ],
                        default="rule",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("source_occurred_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="FitmentReadModel",
            fields=[
                ("offer_uid", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("fitments", models.JSONField(blank=True, default=list)),
                (
                    "crossref_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("risky_family", models.JSONField(blank=True, null=True)),
                ("computed_at", models.DateTimeField()),
                ("source_occurred_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OfferReadModel",
            fields=[
                ("offer_uid", models.CharField(max_length=32, primary_key=True, serialize=False)),
                ("source_key", models.CharField(max_length=64)),
                ("external_key", models.CharField(max_length=512)),
                ("seller_key", models.CharField(db_index=True, max_length=64)),
                ("url", models.URLField(max_length=1024)),
                ("raw_title", models.TextField()),
                ("title_normalized", models.TextField()),
                ("brand", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "part_number",
                    models.CharField(blank=True, db_index=True, max_length=128, null=True),
                ),
                ("part_type", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "authenticity_claim",
                    models.CharField(
                        choices=[
                            ("genuine", "genuine"),
                            ("oem", "oem"),
                            ("aftermarket", "aftermarket"),
                            ("used", "used"),
                            ("refurbished", "refurbished"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("pack_quantity", models.IntegerField(default=1)),
                ("price_toman", models.BigIntegerField(blank=True, null=True)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "in stock"),
                            ("out_of_stock", "out of stock"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("vehicle_hints", models.JSONField(blank=True, default=list)),
                ("vehicle_hints_excluded", models.JSONField(blank=True, default=list)),
                ("overbroad_claim", models.BooleanField(default=False)),
                ("confidences", models.JSONField(blank=True, default=dict)),
                ("extraction_provenance", models.JSONField(blank=True, default=dict)),
                ("normalizer_version", models.CharField(default="", max_length=64)),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_occurred_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="VehicleReadModel",
            fields=[
                (
                    "vehicle_slug",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("brand", models.CharField(default="", max_length=128)),
                ("model", models.CharField(default="", max_length=128)),
                ("trim", models.CharField(blank=True, max_length=128, null=True)),
                ("year_from", models.IntegerField(blank=True, null=True)),
                ("year_to", models.IntegerField(blank=True, null=True)),
                ("engine_code", models.CharField(blank=True, max_length=64, null=True)),
                ("display_name_fa", models.CharField(default="", max_length=255)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("source_occurred_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ClickCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_uid", models.UUIDField()),
                ("offer_uid", models.CharField(max_length=32)),
                ("seller_key", models.CharField(db_index=True, max_length=64)),
                ("clicks", models.BigIntegerField(default=0)),
                ("suspicious_clicks", models.BigIntegerField(default=0)),
                ("last_click_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["product_uid"], name="catalog_cli_product_1c6815_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_uid", "offer_uid"), name="uniq_clickcounter_product_offer"
                    )
                ],
            },
        ),
        # PriceHistory is the one table that grows without bound, so it is
        # range-partitioned by month. Django has no partitioning support, so
        # the model's *state* is declared normally while the *database* side
        # is raw DDL. Everything else about the model — the ORM, the admin,
        # the tests — is unaffected.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PriceHistory",
                    fields=[
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("offer_uid", models.CharField(max_length=32)),
                        ("product_uid", models.UUIDField(blank=True, null=True)),
                        ("observed_at", models.DateTimeField()),
                        ("price_toman", models.BigIntegerField(blank=True, null=True)),
                        (
                            "stock_status",
                            models.CharField(
                                choices=[
                                    ("in_stock", "in stock"),
                                    ("out_of_stock", "out of stock"),
                                    ("unknown", "unknown"),
                                ],
                                default="unknown",
                                max_length=16,
                            ),
                        ),
                    ],
                    options={
                        "indexes": [
                            models.Index(
                                fields=["offer_uid", "observed_at"],
                                name="catalog_pri_offer_u_320873_idx",
                            ),
                            models.Index(
                                fields=["product_uid", "observed_at"],
                                name="catalog_pri_product_401a5d_idx",
                            ),
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("offer_uid", "observed_at"),
                                name="uniq_pricehistory_offer_observed",
                            )
                        ],
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=CREATE_PRICE_HISTORY_SQL,
                    reverse_sql="DROP TABLE IF EXISTS catalog_pricehistory CASCADE;",
                ),
                migrations.RunPython(create_initial_partitions, migrations.RunPython.noop),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic", models.CharField(max_length=128)),
                ("event_id", models.UUIDField()),
                ("entity_key", models.CharField(blank=True, default="", max_length=255)),
                ("occurred_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["processed_at"], name="catalog_pro_process_1d45b5_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("topic", "event_id"), name="uniq_processed_event"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_uid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "title_override",
                    models.CharField(
                        blank=True,
                        help_text="Human title. Sticky across rebuilds.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "part_type",
                    models.CharField(blank=True, db_index=True, max_length=128, null=True),
                ),
                (
                    "authenticity_dominant",
                    models.CharField(
                        choices=[
                            ("genuine", "genuine"),
                            ("oem", "oem"),
                            ("aftermarket", "aftermarket"),
                            ("used", "used"),
                            ("refurbished", "refurbished"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=1024, null=True)),
                ("image_url_override", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "representative_offer_uid",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "representative_override",
                    models.CharField(
                        blank=True,
                        help_text="Human pick. Sticky across rebuilds.",
                        max_length=32,
                        null=True,
                    ),
                ),
                ("representative_reason", models.JSONField(blank=True, default=dict)),
                (
                    "part_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "crossref_codes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "vehicles_compatible",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "vehicles_incompatible",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "vehicles_unknown",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("risky_family_note_fa", models.TextField(blank=True, null=True)),
                ("offer_count", models.IntegerField(default=0)),
                ("min_price_toman", models.BigIntegerField(blank=True, null=True)),
                ("max_price_toman", models.BigIntegerField(blank=True, null=True)),
                ("median_price_toman", models.BigIntegerField(blank=True, null=True)),
                ("price_series", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "unpublished_reasons",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("successor_product_uid", models.UUIDField(blank=True, null=True)),
                (
                    "successor_slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True),
                ),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("document", models.JSONField(blank=True, default=dict)),
                ("document_hash", models.CharField(blank=True, default="", max_length=64)),
                ("related", models.JSONField(blank=True, default=list)),
                ("seller_badges", models.JSONField(blank=True, default=dict)),
                ("click_count", models.BigIntegerField(default=0)),
                ("dirty_since", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_emitted_hash", models.CharField(blank=True, default="", max_length=64)),
                ("last_emitted_at", models.DateTimeField(blank=True, null=True)),
                ("cluster_change_reason", models.CharField(blank=True, default="", max_length=64)),
                ("cluster_computed_at", models.DateTimeField(blank=True, null=True)),
                ("source_occurred_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["part_type", "is_published"], name="catalog_pro_part_ty_4fbea8_idx"
                    ),
                    models.Index(
                        fields=["successor_product_uid"], name="catalog_pro_success_70b5d2_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["crossref_codes"], name="idx_product_crossrefs"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["part_numbers"], name="idx_product_partnumbers"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["vehicles_compatible"], name="idx_product_vehicles"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("seller_key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "name_is_override",
                    models.BooleanField(
                        default=False,
                        help_text="A human set the name; recomputation leaves it alone.",
                    ),
                ),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("source_key", models.CharField(blank=True, max_length=64, null=True)),
                ("is_panel", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("standard", "standard"),
                            ("trusted", "trusted"),
                            ("suspended", "suspended"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "tier_override",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "new"),
                            ("standard", "standard"),
                            ("trusted", "trusted"),
                            ("suspended", "suspended"),
                        ],
                        help_text="Human decision. Wins over the computed tier, permanently.",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("trust_score", models.FloatField(default=0.0)),
                ("price_observations", models.IntegerField(default=0)),
                ("price_hits", models.IntegerField(default=0)),
                ("stock_observations", models.IntegerField(default=0)),
                ("stock_hits", models.IntegerField(default=0)),
                ("price_accuracy", models.FloatField(blank=True, null=True)),
                ("stock_accuracy", models.FloatField(blank=True, null=True)),
                ("domain_age_days", models.IntegerField(blank=True, null=True)),
                ("contact_completeness", models.FloatField(blank=True, null=True)),
                ("has_trust_badge", models.BooleanField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("last_emitted_hash", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "ordering": ["seller_key"],
                "indexes": [models.Index(fields=["tier"], name="catalog_sel_tier_79322d_idx")],
            },
        ),
        migrations.CreateModel(
            name="ProductOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("offer_uid", models.CharField(db_index=True, max_length=32)),
                ("membership_confidence", models.FloatField(default=0.0)),
                (
                    "membership_provenance",
                    models.CharField(
                        choices=[
                            ("rule", "rule"),
                            ("model", "model"),
                            ("human", "human"),
                            ("catalog", "catalog"),
                            ("consensus", "consensus"),
                        ],
                        default="rule",
                        max_length=16,
                    ),
                ),
                ("seller_key", models.CharField(max_length=64)),
                ("seller_name", models.CharField(max_length=255)),
                ("price_toman", models.BigIntegerField(blank=True, null=True)),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "in stock"),
                            ("out_of_stock", "out of stock"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "authenticity_claim",
                    models.CharField(
                        choices=[
                            ("genuine", "genuine"),
                            ("oem", "oem"),
                            ("aftermarket", "aftermarket"),
                            ("used", "used"),
                            ("refurbished", "refurbished"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("trust_score", models.FloatField(default=0.0)),
                ("rank_position", models.IntegerField(default=0)),
                ("rank_score", models.FloatField(default=0.0)),
                ("url", models.URLField(max_length=1024)),
                ("is_cheapest", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["rank_position", "offer_uid"],
                "indexes": [
                    models.Index(fields=["seller_key"], name="catalog_pro_seller__366d5e_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "offer_uid"), name="uniq_product_offer"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductSlug",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=255, primary_key=True, serialize=False
                    ),
                ),
                ("is_current", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slugs",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "is_current"], name="catalog_pro_product_724e14_idx"
                    )
                ],
            },
        ),
    ]
