# Generated by Django 5.2.17 on 2026-08-22 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrossReference",
            fields=[
                ("pair_key", models.CharField(max_length=260, primary_key=True, serialize=False)),
                ("code_a", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("code_b", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("confidence", models.FloatField(default=0.0)),
                ("provenance", models.CharField(blank=True, default="", max_length=32)),
                ("active", models.BooleanField(default=True)),
                ("event_occurred_at", models.DateTimeField()),
                ("index_applied_at", models.DateTimeField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductState",
            fields=[
                ("product_uid", models.UUIDField(primary_key=True, serialize=False)),
                ("payload", models.JSONField(default=dict)),
                (
                    "part_type",
                    models.CharField(blank=True, db_index=True, max_length=128, null=True),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("event_occurred_at", models.DateTimeField()),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                ("index_applied_at", models.DateTimeField(blank=True, null=True)),
                ("embedding", models.JSONField(default=list)),
                ("embedding_text_hash", models.CharField(blank=True, default="", max_length=64)),
                ("trace_id", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "query_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("normalized_text", models.TextField(db_index=True)),
                (
                    "vehicle_slug",
                    models.CharField(blank=True, db_index=True, max_length=128, null=True),
                ),
                ("filters", models.JSONField(default=dict)),
                ("result_count", models.PositiveIntegerField(db_index=True, default=0)),
                ("result_product_uids", models.JSONField(default=list)),
                ("clicked_position", models.PositiveIntegerField(blank=True, null=True)),
                ("clicked_product_uid", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReindexRun",
            fields=[
                (
                    "run_uid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("consumer_group", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(db_index=True, default="running", max_length=16)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SynonymDecision",
            fields=[
                (
                    "request_uid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("token", models.CharField(blank=True, default="", max_length=255)),
                (
                    "part_type",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("decision", models.CharField(blank=True, default="", max_length=32)),
                ("active", models.BooleanField(default=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("event_occurred_at", models.DateTimeField()),
                ("index_applied_at", models.DateTimeField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleState",
            fields=[
                (
                    "vehicle_slug",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("payload", models.JSONField(default=dict)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("event_occurred_at", models.DateTimeField()),
                ("trace_id", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ProductPartNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=128)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_part_numbers",
                        to="search.productstate",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "code"), name="search_unique_product_part_number"
                    )
                ],
            },
        ),
    ]
